.*: Assembler messages:
.*: Error: Instruction cv.addn requires absolute expression
.*: Error: Instruction cv.addun requires absolute expression
.*: Error: Instruction cv.addrn requires absolute expression
.*: Error: Instruction cv.addurn requires absolute expression
.*: Error: Instruction cv.subn requires absolute expression
.*: Error: Instruction cv.subun requires absolute expression
.*: Error: Instruction cv.subrn requires absolute expression
.*: Error: Instruction cv.suburn requires absolute expression
