.*: Assembler messages:
.*: Error: immediate value must be 5-bit signed, -17 is out of range
.*: Error: immediate value must be 5-bit signed, -32 is out of range
.*: Error: immediate value must be 5-bit signed, 16 is out of range
.*: Error: immediate value must be 5-bit signed, 44 is out of range
.*: Error: immediate value must be 5-bit signed, -17 is out of range
.*: Error: immediate value must be 5-bit signed, -32 is out of range
.*: Error: immediate value must be 5-bit signed, 16 is out of range
.*: Error: immediate value must be 5-bit signed, 44 is out of range
