.*: Assembler messages:
.*: Error: unrecognized opcode `cv.starti 1,320', extension `xcorevhwlp' or `xcorev' required
.*: Error: unrecognized opcode `cv.endi 1,1056', extension `xcorevhwlp' or `xcorev' required
.*: Error: unrecognized opcode `cv.setupi 1,488,12', extension `xcorevhwlp' or `xcorev' required
.*: Error: unrecognized opcode `cv.setup 1,t5,488', extension `xcorevhwlp' or `xcorev' required
.*: Error: unrecognized opcode `cv.count 1,a1', extension `xcorevhwlp' or `xcorev' required
.*: Error: unrecognized opcode `cv.counti 1,1937', extension `xcorevhwlp' or `xcorev' required
