.*: Assembler messages:
.*: Error: unrecognized opcode `cv.starti 1,320', extension `xcvhwlp' or `xcv' required
.*: Error: unrecognized opcode `cv.endi 1,1056', extension `xcvhwlp' or `xcv' required
.*: Error: unrecognized opcode `cv.setupi 1,488,12', extension `xcvhwlp' or `xcv' required
.*: Error: unrecognized opcode `cv.setup 1,t5,488', extension `xcvhwlp' or `xcv' required
.*: Error: unrecognized opcode `cv.count 1,a1', extension `xcvhwlp' or `xcv' required
.*: Error: unrecognized opcode `cv.counti 1,1937', extension `xcvhwlp' or `xcv' required
