.*: Assembler messages:
.*: Error: -1 constant out of range for cv.counti, range:\[0, 4095\]
.*: Error: -1 constant out of range for cv.setupi, range:\[0, 4095\]
.*: Error: -832 constant out of range for cv.counti, range:\[0, 4095\]
.*: Error: -291 constant out of range for cv.setupi, range:\[0, 4095\]
.*: Error: 4096 constant out of range for cv.counti, range:\[0, 4095\]
.*: Error: 4096 constant out of range for cv.setupi, range:\[0, 4095\]
.*: Error: 74285 constant out of range for cv.counti, range:\[0, 4095\]
.*: Error: 8334 constant out of range for cv.setupi, range:\[0, 4095\]
