.*: Assembler messages:
.*: Error: unrecognized opcode `c.mul a0,a1', extension `zcb' and `zmmul', or `zcb' and `m' required
.*: Error: unrecognized opcode `c.sext.b a0', extension `zcb' and `zbb' required
.*: Error: unrecognized opcode `c.sext.h a0', extension `zcb' and `zbb' required
.*: Error: unrecognized opcode `c.zext.h a0', extension `zcb' and `zbb' required
.*: Error: unrecognized opcode `c.zext.w a0', extension `zcb' and `zba' required
.*: Error: unrecognized opcode `c.zext.b a0', extension `zcb' required
.*: Error: unrecognized opcode `c.sext.w a0', extension `zcb' required
.*: Error: unrecognized opcode `c.not a1', extension `zcb' required
