[^:]*: Assembler messages:
[^:]*:.*: Error: unrecognized opcode `c.lbu x9,1\(x8\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x15,2\(x15\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x8,3\(x8\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x15,1\(x9\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x15,2\(x12\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x13,1\(x15\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x14,0\(x15\)'
[^:]*:.*: Error: unrecognized opcode `c.lbu x8,\(x15\)'

