.*: Assembler messages:
.*:.*: Error: unrecognized opcode `cm.sb x8,2\(x10\)'
.*:.*: Error: unrecognized opcode `cm.sb x15,1\(x12\)'
.*:.*: Error: unrecognized opcode `cm.sb x8,3\(x9\)'
.*:.*: Error: unrecognized opcode `cm.sb x9,2\(x8\)'
.*:.*: Error: unrecognized opcode `cm.sb x12,1\(x8\)'
.*:.*: Error: unrecognized opcode `cm.sb x13,3\(x15\)'
.*:.*: Error: unrecognized opcode `cm.sb x14,0\(x15\)'
