.*: Assembler messages:
.*: Error: unrecognized opcode `c.lhu x9,2\(x14\)'
.*: Error: unrecognized opcode `c.lhu x11,2\(x15\)'
.*: Error: unrecognized opcode `c.lhu x8,0\(x8\)'
.*: Error: unrecognized opcode `c.lhu x9,0\(x9\)'
.*: Error: unrecognized opcode `c.lhu x8,2\(x12\)'
.*: Error: unrecognized opcode `c.lhu x13,2\(x15\)'
.*: Error: unrecognized opcode `c.lhu x14,0\(x14\)'
.*: Error: unrecognized opcode `c.lhu x11,\(x8\)'
