.*: Assembler messages:
.*: Error: unrecognized opcode `c.lh x9,2\(x14\)'
.*: Error: unrecognized opcode `c.lh x11,2\(x15\)'
.*: Error: unrecognized opcode `c.lh x8,0\(x8\)'
.*: Error: unrecognized opcode `c.lh x9,0\(x9\)'
.*: Error: unrecognized opcode `c.lh x8,2\(x12\)'
.*: Error: unrecognized opcode `c.lh x13,2\(x15\)'
.*: Error: unrecognized opcode `c.lh x14,0\(x14\)'
.*: Error: unrecognized opcode `c.lh x11,\(x8\)'
