.*: Assembler messages:
.*:.*: Error: unrecognized opcode `c.sb x9,1\(x8\)'
.*:.*: Error: unrecognized opcode `c.sb x15,2\(x15\)'
.*:.*: Error: unrecognized opcode `c.sb x8,3\(x8\)'
.*:.*: Error: unrecognized opcode `c.sb x15,1\(x9\)'
.*:.*: Error: unrecognized opcode `c.sb x15,2\(x12\)'
.*:.*: Error: unrecognized opcode `c.sb x13,1\(x15\)'
.*:.*: Error: unrecognized opcode `c.sb x14,0\(x15\)'
.*:.*: Error: unrecognized opcode `c.sb x8,\(x15\)'
