[^:]*: Assembler messages:
[^:]*:.*: Error: unrecognized opcode `cm.lbu x8,2\(x10\)'
[^:]*:.*: Error: unrecognized opcode `cm.lbu x15,1\(x12\)'
[^:]*:.*: Error: unrecognized opcode `cm.lbu x8,3\(x9\)'
[^:]*:.*: Error: unrecognized opcode `cm.lbu x9,2\(x8\)'
[^:]*:.*: Error: unrecognized opcode `cm.lbu x12,1\(x8\)'
[^:]*:.*: Error: unrecognized opcode `cm.lbu x13,3\(x15\)'
[^:]*:.*: Error: unrecognized opcode `cm.lbu x14,0\(x15\)'
