[^:]*: Assembler messages:
[^:]*:.*: Error: unrecognized opcode `cm.lhu x8,2\(x8\)'
[^:]*:.*: Error: unrecognized opcode `cm.lhu x15,0\(x15\)'
[^:]*:.*: Error: unrecognized opcode `cm.lhu x8,2\(x14\)'
[^:]*:.*: Error: unrecognized opcode `cm.lhu x15,2\(x13\)'
[^:]*:.*: Error: unrecognized opcode `cm.lhu x9,0\(x12\)'
[^:]*:.*: Error: unrecognized opcode `cm.lhu x8,2\(x15\)'
[^:]*:.*: Error: unrecognized opcode `cm.lhu x12,0\(x14\)'
