.*: Assembler messages:
.*: Error: unrecognized opcode `c.sh x9,2\(x9\)'
.*: Error: unrecognized opcode `c.sh x15,2\(x15\)'
.*: Error: unrecognized opcode `c.sh x8,0\(x8\)'
.*: Error: unrecognized opcode `c.sh x9,0\(x9\)'
.*: Error: unrecognized opcode `c.sh x12,2\(x12\)'
.*: Error: unrecognized opcode `c.sh x13,2\(x13\)'
.*: Error: unrecognized opcode `c.sh x14,0\(x14\)'
.*: Error: unrecognized opcode `c.sh x8,\(x8\)'
