.*Assembler messages:
.*:.*: Error: unrecognized opcode `cm.push.e \{ra\},-64'
.*:.*: Error: unrecognized opcode `cm.pop.e \{ra\},64'
.*:.*: Error: unrecognized opcode `cm.popret.e \{ra\},64'
.*:.*: Error: unrecognized opcode `cm.popretz.e \{ra\},64'
.*:.*: Error: unrecognized opcode `cm.mva01s.e s0,s7'
.*:.*: Error: unrecognized opcode `cm.mvsa01.e s0,s7'
.*:.*: Error: unrecognized opcode `cm.jt 512'
.*:.*: Error: unrecognized opcode `cm.jalt 8'
