.*: Assembler messages:
.*: Error: illegal operands `c.slli '
.*: Error: illegal operands `c.slli ,'
.*: Error: illegal operands `c.slli ,1'
.*: Error: illegal operands `c.slli x1,'
.*: Error: illegal operands `c.slli x1,x2,4'
.*: Error: illegal operands `c.slli 4,1'
.*: Error: illegal operands `c.slli x0,0'
.*: Error: illegal operands `c.slli x1,-1'
.*: Error: illegal operands `c.slli x1,1.0'
.*: Error: illegal operands `c.slli x1,64'
.*: Error: illegal operands `c.slli x1,x8'

